# Generated by Django 6.0.3 on 2026-03-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_webhooksubscription_webhookattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooksubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebhookAttempt',
        ),
        migrations.DeleteModel(
            name='WebhookSubscription',
        ),
    ]
